name: Notify Discord webhook of release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.31.0
        with:
          php-version: 8.2

      - name: Restore Composer package cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            composer-v2-cache-
            
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Get actual tag name
        id: tag-name
        run: echo "TAG_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV

      - name: Debugging step
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Tag Name: $TAG_NAME"
          echo "GitHub Token: ${{ secrets.GITHUB_TOKEN }}"
          echo "Discord Webhook URL: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}"
          echo "Ping Role ID: ${{ secrets.DISCORD_NEWS_PING_ROLE_ID }}"
          
      - name: Run webhook post script
        run: php .github/workflows/discord-release-embed.php ${{ github.repository }} $TAG_NAME ${{ secrets.GITHUB_TOKEN }} ${{ secrets.DISCORD_RELEASE_WEBHOOK }} ${{ secrets.DISCORD_NEWS_PING_ROLE_ID }}
